### ISSUE TITLE
H2 - reason for not sampling a trip

### ISSUE THREAD

**Issue by mrska** [ices-tools-dev/RDBES#12]
Hi,

If I'm using H2 and a vessel list as a proxy and the fishermen refuses to take an observer how should I fill in all the details of the fishing trip?
Is it a good approach to at the  end of the year, check when was the first trip after the contact and put the details of this trip into FT table? Or in case of refusal should I just not include it in the FT?

**Comment by davidcurrie2001** [comment]
In the FishingTrip table you could put FTsampled = "No" and give a reason in the FTreasonNotSampled field, but you would still need to provide the mandatory fields (e.g. FTarrivalLocation, FTarrivalDate, etc.) - as you say perhaps you could use the trip details from the first trip recorded after the refusal for this.
I think in this case if you were using H1 it would be clearer because you would have an entry in the VesselSelection table for the vessel you have picked, and then say VSsampled = "No" and give a relevant VSreasonNotSampled.

**Comment by mrska** [comment]
Yes, that's right that in H1 there would not be any problem with this. We are  just trying to fill in both hierarchies and see what problem we have with each of them. 
Thank you for the answear.
