### ISSUE TITLE
EEZ instad of EEZI

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#141]
While creating a new exchange format to be used for HAWG sandeel i realixed that the EEZ codes are not real EEZ, but an indicator.

Would it be possible to include the actual EEZ e.g. EEC, NOR.

The EEZI is present in CL, CE and CS data.

The reason for using this in respect to sandeel is to try to create a mangement area for Norwegian waters, so I can't use the present codes.

I guess the FDI EEZI can be created based on the EEZ, but not sure.

**Comment by josefineegekvist** [comment]
Core group meeting 2022/02/23: It could be possible to use the EEZ instead of EEZI (EEZ indicator). The existing EEZI have the codes: COAST, EU, RFMO (RFMO are non-EU and coastal waters). It is suggested to change to EEZ with the following codes: country code (the ISO_3166) and EU and International waters, **International waters would need to be added to the ISO_3166**. The EEZ is needed for sandeel because of the management areas. EEZI is now a mandatory field, it is suggested to make in optional in all tables, therefore the EEZ should also be optional. The EEZI is needed for the FDI data call, if countries want to do the FDI data export, then the countries have to fill in the EEZ. The Core Group agreed to make these changes.

**Comment by HenrikK-N** [comment]
Since it was not possible to add the 3 codes from EEZI to the code list ISO_3166. It was agreed to add the EEZI field again in CL and CE.

**Comment by HenrikK-N** [comment]
The field EEZI 'CXexclusiveEconomicZoneIndicator' was added again in CL and CE. After it was added and then changed to EEZ (country code), because it was not possible to add EU, adn International waters to the countrie codes ISO_3166. So now there is both the EEZ and EEZI fields in CL and CE as optional fields.
