### ISSUE TITLE
Hierarchy 13 - why is FT not mandatory?

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBES#144]
Reviewing a map between RDB and RDBES for WKBIOPTIM and looking for vessel flag country I became a bit puzzled by hiererchy 13.

Encrypted vessel code is mandatory in VS, FT and LE and one/more of these tables are mandatory in all of the hierarchies - except 13. 

Why is FT not a mandatory table outside the hierarchy? it seems a bit strange to sample a FO without knowing the FT.

**Comment by edvinf** [comment]
FT-parameters are probably obtainable in most cases, but not necessarily, and it may at least be tricky for non-response records. Since FT is not part of the hierarchy, I think it is best to be cautious about making stuff mandatory.

**Comment by KirstenBirchHaakansson** [comment]
TRUE that it may be tricky with non-responses and I guess that will be tricky in most hiererchies, but I still think it is a bit strange to sample a haul without knowing the FT, but if it is the case then it is

**Comment by edvinf** [comment]
I agree, but I think it being strange is not sufficient reason to complicate matters for data submitters. I think we should come up with a realistic and strong use-case for these data in order to make them mandatory. For the purposes we are using it, it seems to be possible to get FT-data, even for nonresponse, but it has not been tested yet.

Hierarchy 13 is implemented to serve a particular probabilistic sampling scheme, but via the samplinghiearchycorrect-flag, it also serve as an option for sampling programmes where the hierarchy is particularly tricky to identify, and an option for historical data where unrecorded information can be lost (like links to vessel registries). While we don't want to encourage this as an easy opt-out, I think it serves a purpose to have a minimal hierarchy for these cases. H13 was not designed for that purpose, and could probably be simplified even further if that was the goal, but it is worth keeping that function of the hierarchy in mind as well.

**Comment by HenrikK-N** [comment]
It was agreed to keep things as they are.
