### ISSUE TITLE
"fixed" as sampling method?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBES#15]
Some countries sample a fixed set of ports. One possibility is that they declare that as "Expert judgement (NPEJ)" but that does not quite represent what is needed. It is more something like "fixed selection (NPFIX)" - add FAQ? open code and add to documentation?

**Comment by jsrodriguezieo** [comment]
That give more information concerning the port procedures, but sample selection methods refers to how the selection is done. With that NPFIX you lost how that selection was done (you could have done ad hoc and then fix). In our case we select most important ports based on PSU activity during the reference years. It is, in my understanding, a NPEJ. May be a NPEJFI would add to that the fact that selection is fixed later.

**Comment by nmprista** [comment]
NPFIX or NPEJFI may potentially be useful for plans that select eg, always the same 30 weeks of the 52 weeks in year to sample

**Comment by Ruth-R-Kelly** [comment]
I was about to add a very similar issue, but I think this one covers it.  In our case we sample in set weeks of the year (ca. 48 of 52). The same weeks are unsampled in every year (e.g. Christmas week etc.).  We use a H3 with a TE table and a row for all sampling weeks. The table has 52 rows as we decided that the unsampled weeks should be included in the table, as they could be concidered to be in the sampling frame. So we sample 48 of 52 weeks, via what is concidered a NPEJ design. The probability of selection is 0 or 1 for each week, with some weeks having no chance of being sampling under the design.  The alternative way to make this table would be to include only the 48 weeks that we always sample, and call it a 'CENSUS' design.  Or as nmprista suggests something like NPEJFI might work as a new code. Calling it a 'CENSUS', becomes less comfortable conceptually for shorter sampling seasons (e.g. 12 weeks, one from each month, even if these are fixed in their selection and represent the full year).  I'm going with the including the 52 weeks in the table, and calling the selection NPEJ, and using the probabilities and the TEsampled column to explain the probabilities for now. But interested to know what others think of this.

**Comment by nmprista** [comment]
Humm...nice arguments!

After reading you I pend towards a guideline that does not involve a new NPEJFIX. What about if your fixed sampling would be treated as NPEJ with probability of inclusion == 1? The latter probability basically points out the fixed strategy, no? 

In the case of @jsrodriguezieo this could mean: totalN=20 ports, n=7 ports, method = NPEJ, probInclusion=1
In the case of @Ruth-R-Kelly this could mean: totalN=52 weeks, n=48 weeks, method = NPEJ, probInclusion = 1
In the 2nd case of @Ruth-R-Kelly this could mean: totalN=52 weeks, b=12 weeks, method = NPEJ, probInclusion = 1

How does this sound to you?

**Comment by Ruth-R-Kelly** [comment]
Thanks nmprista. Sounds good to me.  In that case do I include the unsampled weeks as rows in the TE table? i.e. they are in the TotalN of 52, but the probInclusion for these weeks is 0 ? Or do I omit them, since they can be inferred from the info in the other 48 rows?

**Comment by HenrikK-N** [comment]
The core group provisional advice:

In the case of @jsrodriguezieo this could mean: **totalN=7** ports, n=7 ports, method = NPEJ, probInclusion=1 (Though 20 ports)
In the case of @Ruth-R-Kelly this could mean: **totalN=48** weeks, n=48 weeks, method = NPEJ, probInclusion = 1 (Though 52 weeks)
In the 2nd case of @Ruth-R-Kelly this could mean: **totalN=12** weeks, b=12 weeks, method = NPEJ, probInclusion = 1 (Though 52 weeks)

This topic will be further discussed at WGCATCH intersession in August.

**Comment by Ruth-R-Kelly** [comment]
Hi, 
I have a related question about the use of 'CENSUS' vrs 'NPAH/NPEJ' where the intension is the sample all units, but for some reason some are unsampled.   

Say for example, in Hierarchy 3, we have a Trip with 6 hauls. Our intension is always to sample all Hauls. So usually all Hauls are selected, (total N = 6, sampled N = 6), and selection method in CENSUS. But on occaisional trips for some reason not all hauls are sampled (e.g. time constraints, or FOvalidity problems etc.). Do we on those rows in the FO table declare the selection method to be different (e.g. NPAH/NPEJ), or leave the FOselectionMethod as CENSUS (i.e. method in the protocol), and only specify that some hauls were unsampled using the FOnumberSampled and the FOsampled field. 

Thanks in advance, Ruth

**Comment by edvinf** [comment]
I would treat it exactly as other selection methods, and make a row for each haul since each haul was selected, and flag those selected but not sampled in FOsampled. FOnumberSampled should somewhat unintuitively be equal to FOnumberTotal even when some were not sampled. The naming of these fields does not reflect the distinction between selection and sampling. 

There is an example in the chapter "New features of the RDBES" in "RDBES Documentation of the Data Model.docx", which I think can be followed also for CENSUS-selections. You may find that the names of codes in that example need updating.

Considering the documentetion and field description, I think we should keep the field names as they are at this point. We may consider making the distinction between selection and sampling clearer in the fields descriptions for the XXnumberSampled fields.

**Comment by Ruth-R-Kelly** [comment]
Thanks Edvin, 

That's very helpful.  

So in this example, if total N = 6, FOnumberSampled = 6 (i.e. 6 were selected, even if later unsampled), and selection method remains CENSUS. The FOsampled field is the only field that indicates that some of the hauls were unsampled (i.e. a value of "no" for any unsampled rows). 

The FOnumberSampled remaining the same as the total N is indeed counter-intuitive to me, but I do understand the logic now that you tell me about it. Thank you for pointing that out. 

Best regards, 

Ruth

**Comment by davidcurrie2001** [comment]
Yes, with hindsight perhaps XXnumberSelected would have been a better name for these fields

**Comment by Ruth-R-Kelly** [comment]
Hindsight is 20/20 ;) Perhaps it could be changed in the future, but for now I think it works as is.

**Comment by edvinf** [comment]
I consider the opening issue resolved by the new selection methods, and propose that we close this issue once the new codes are in effect. I have made a separate issue to follow up concerns that came up in comments (#117). If you find that there are other concerns in the comments that are not currently being tracked, please record issues for those as well so that this issue can be closed once the opening issue is resolved.

**Comment by nmprista** [comment]
Discussion at estimation subgroup 2021-06-24
- issue closed [FIXED has been added to code list]
