### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by BergenCalling** [ices-tools-dev/RDBES#16]
The search function vocab.ices.dk requires very specific search words to return the requested answer. I.e. when searching for "metier 6" the only option is to search for "metier6" to return a result. It would be very helpful if you could search for the field name directly in the search engine. And/or provide an explicit description of each field at each level (tables) of the model.

**Comment by edvinf** [comment]
Thank you for reporting. The data model documentation (https://github.com/ices-tools-dev/RDBES/blob/master/Documents/RDBES%20Data%20Model.xlsx) has now been updated with precise names for code lists (columns 'Vocabulary code type'), which can be used as search term on vocab.ices.dk in order to get the code list for a field. See also issue https://github.com/ices-tools-dev/RDBES/issues/36 .
