### ISSUE TITLE
Unknown CLscientificWeight

### ISSUE THREAD

**Issue by edvinf** [ices-tools-dev/RDBES#205]
How does one deal with unknown scientific weights in the CL table?

I do not want to indicate that the official weight is fit for use without having some explicit consideration behind it, so I have adopted the convention of setting scientific weight to 0 for species where I know there may be issues with official weights, or where I have not been able to explicitly consider the applicability of official weights.

If this is the recommended approach, I think it would be nice to have a code to indicate it in either CLExplainDifference, or CLdataTypeOfScientificWeight.

Another option could be to have the value "Unknown" accepted, as is done for CLlandingsValue.

**Comment by HenrikK-N** [comment]
The Core Group suggest in this case to enter the official weight in the scientific weight, because the scientific weight is the weight used in the assessment (the most important weight), therefore the scientific weight should be filled in, with the best known weight. If the weight is doubtful, it is suggested to mark it using the filed CLscientificWeightQualitativeBias and indicate if the scientific weight is highly overestimated (using '+++') or highly underestimated (using '---').
