### ISSUE TITLE
CL species codes (CLspeciesFaoCode) - SpecASFIS in ICES vocabulary

### ISSUE THREAD

**Issue by josefineegekvist** [ices-tools-dev/RDBES#26]
The SpecASFIS in the ICES vocabulary only contain 179 species codes, while the SpecWoRMS contain 870 species codes. The species list processed by the RCG ISSG on Metier issues contain 1064 species codes of commercial species uploaded to Eurostat. Can the SpecASFIS list be updated with the species codes from the species list from the Metier group?
[2020.06.05_Species list_differences.xlsx](https://github.com/ices-tools-dev/RDBES/files/4790585/2020.06.05_Species.list_differences.xlsx)

**Comment by edvinf** [comment]
In order to help identifying errors, we encourage users experiencing this kind of problem to provide a valid aphia id that reproduce the problem. That is, an aphia id that has status 'accepted'. Status of aphia ids can be checked by entering the aphia id into the search box at: http://www.marinespecies.org

**Comment by HenrikK-N** [comment]
For now we need to work on the mapping between FAO ASFIS species codes and AphiaId code. Since the FAO ASFIS code is optional please leave the field for now. When the mapping and the code list is updated, we will let you know and you can add it.
