### ISSUE TITLE
SAlowerHierarchy field not optional

### ISSUE THREAD

**Issue by Eucrow** [ices-tools-dev/RDBES#49]
In the documentation the field SAlowerHierarchy has this description:
`
The Lower Hierarchy that will be used for this Sample.  Mandatory if there is data linked directly to this sample/subsample, Optional is this sample only links to subsamples.
`
Besides, the required column of this field specifies M/O.

But if I try to upload a file with this field empty and without any child, an error is thrown:
`7 | 'SAlowerHierarchy' |   | Enumeration | The 'SAlowerHierarchy' element is invalid`

To reproduce this error, there is an example of the file:
```
DE,National Routine,NatRouCF,2019,IEO_M_BC_AC,Y,5
SD,ES,353
OS,1,ESGIJ,Yes,ESGIJ,2019-02-04,,Q1,No,U,Observer,,,14,3,,,NPEJ,1,Market,,,,,,Y,
FT,204876,,No,U,No,U,Observer,On-Shore,,,,,ESGIJ,2019-02-04,,,,,,NPEJ,201900431,,,,,,Y,
LE,204876,No,1,,U,No,U,Observer,N,Lan,ESGIJ,Port,ES,2019-02-04,,EU,27.8.a,21E5,NA,,,OTB_DEF,OTB_DEF_>=70_0_0,OTB,,,,,Unknow,,,,,,NPEJ,201900431,,,,,,Y,,Yes
SS,1,No,sort,Lan,vol,U,No,U,Observer,IEO_M_SAP_DCF,N,,,,,CENSUS,IEO_M_SAP_DCF,,,,,,Y,
SA,1,,No,U,105814,SYC,Whole,NotDetermined,Lan,HuC,ES-IEO,11,U,,,,NA,,,,,,,,,Box,786800,,,,,,NPEJ,,,Observer,N,,,700,,
```

Thanks.

**Comment by edvinf** [comment]
Hi.

The field description of SAlowerHierarchy does not explicitly cover the case when a sample is recorded and no biological measurements are taken. But I believe that it is possible to put in a value for  SAlowerHierarchy without actually providing any lower-hierarchy lines for that sample. Hopefully that can be a short-term solution for you in order to progress with data uploads.

We should perhaps clarify the field description to cover the case when a SA-record is provided in order to for example describe catch composition, when no biological variables are measured.

In case you are trying to record subsampling: The provided example does not specify "a sample that only links to subsamples" (text from field description). Subsampling is specified with SA-records following the initial SA record, where a "SAparentSequencenumber" is provided.

**Comment by Eucrow** [comment]
Thank you @edvinf 

I already tested your suggestions: if a hierarchy is put in SAlowerHierarchy without any line for that lower hierachy, the app return this error:

`7 | There must exists at least one FM element under SA record`

In fact, I'm trying to record subsampling as you said, too. If I have a SA record, with "B" in SAlowerHierarchy, followed by a SA record with a SAparentSequenceNumber provided with the SAsequenceNumber of the previous SA record, the app throws the previous error. If I try to upload without any value in SAlowerHierarchy, it throws the invalid element error.

Anyway, we are interested in both cases, allow to upload a SA record without biological variables measured, only catch composition, and allowed SA records with subsampling.

Here is the extract of H5 hierarchy with SAparentSequenceNumber and FM records:

```
DE,National Routine,NatRouCF,2019,IEO_M_BC_AC,Y,5
SD,ES,353
OS,1,ESGIJ,Yes,ESGIJ,2019-02-04,,Q1,No,U,Observer,,,14,3,,,NPEJ,1,Market,,,,,,Y,
FT,204876,,No,U,No,U,Observer,On-Shore,,,,,ESGIJ,2019-02-04,,,,,,NPEJ,201900431,,,,,,Y,
LE,204876,No,1,,U,No,U,Observer,N,Lan,ESGIJ,Port,ES,2019-02-04,,EU,27.8.a,21E5,NA,,,OTB_DEF,OTB_DEF_>=70_0_0,OTB,,,,,Unknow,,,,,,NPEJ,201900431,,,,,,Y,,Yes
SS,1,No,sort,Lan,vol,U,No,U,Observer,IEO_M_SAP_DCF,N,,,,,CENSUS,IEO_M_SAP_DCF,,,,,,Y,
SA,1,,No,U,105814,SYC,Whole,NotDetermined,Lan,HuC,ES-IEO,11,U,,,,NA,,,,,,,,,Box,700,,,,,,NPEJ,,B,Observer,N,,,700,,
SA,2,1,No,U,105814,SYC,Whole,NotDetermined,Lan,HuC,ES-IEO,11,F,,,,NA,,,,,,,,,Box,,100,,,,,NPEJ,,B,Observer,Y,,,,100,1
FM,550,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,570,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,580,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,590,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,600,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,610,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,620,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,630,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,640,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,650,1,Total Length,Measured by hand with caliper,cm,Observer,,
SA,3,1,No,U,105814,SYC,Whole,NotDetermined,Lan,HuC,ES-IEO,11,M,,,,NA,,,,,,,,,Box,,20,,,,,NPEJ,,B,Observer,Y,,,,20,1
FM,550,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,570,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,580,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,590,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,600,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,610,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,620,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,630,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,640,1,Total Length,Measured by hand with caliper,cm,Observer,,
FM,660,1,Total Length,Measured by hand with caliper,cm,Observer,,
```

**Comment by davidcurrie2001** [comment]
We had specified lower hierarchy D to cover the case where you had a sample with no biological or length data recorded - does this work for your data?

**Comment by edvinf** [comment]
Thanks David. The code 'D' in SAlowerHierarchy should be used to encode that no biological measurements where taken from the sample. I had forgotten that, but found it described in the "RDBES Documentation of the Data Model.docx". I have created a separate issue to get proper code descriptions in the ICES vocabulary for this code list, so that the definitions are easier to find. Until code lists are updated you may refer to this issue for definitions: https://github.com/ices-tools-dev/RDBES/issues/50

Let us know if that solves the issue with samples with no biological, and I'll look into the subsampling part shortly.

**Comment by Eucrow** [comment]
Thanks @davidcurrie2001 and @edvinf 
I didn't notice the hierarchy 'D'. This solves our problem with the samples without biological mesurementes. :) So, this field should be allways filled with any of the hierarchies, right? If this is the case the field shouldn't be optional in RDBES data model excel file.

**Comment by edvinf** [comment]
I think the intention is that it should be filled blank for samples that are subsampled, but where no biological measurements are taken from the parent sample. We should perhaps consider revising this, but it seems to me that we have a bug with the subsampling even if lowerHierrachy is filled for the parent sample. I will report this to developers.

**Comment by edvinf** [comment]
For the subsampling, I have sent the following bug report to RDBsupport <RDBsupport@ices.dk>:

Uploading of subsamples seems to not validate when formatted according to specification. The field description states that the SAlowerHierarchy field is optional if a sample only links to subsamples. The attachment herringlottery_subsample_H13.csv is encoded without SAlowerHierarchy in the parent sample and gives an enumeration error during schema validation.

I also tried to fill in the SAlowerHierarchy with the value ‘D’ for the parent sample (attachment: herringlottery_subsample_v2_H13.csv). That failed in duplication checking, which may indicate a different problem.

**Comment by edvinf** [comment]
There are some issues with duplication checks that may prevent problems in some subsampling. This is recorded in a different issue: https://github.com/ices-tools-dev/RDBES/issues/51

**Comment by edvinf** [comment]
What remains of this issue is for the core-group to make a decision on the conditional optional status of SAlowerHierarchy. Currently it is implemented as if it was mandatory, and some work would need to be invested to accomodate it differently. If we can use the code 'D' for a parent sample that "only links to subsamples", we only need to update the field description, and no changes need to be made to the enumaration check.

**Comment by davidcurrie2001** [comment]
Updated the documentation to make the field mandatory and added "Use value 'D' if this sample only links to sub-samples."

**Comment by davidcurrie2001** [comment]
Closing this issue - we can re-open if there are any further problems with this approach.
